### ISSUE TITLE
address some api and style issues

### ISSUE THREAD

**Issue by travisstaloch** [travisstaloch/flatbufferz#3]
from https://github.com/travisstaloch/flatbufferz/issues/2#issuecomment-1583068799 by @clickingbuttons

Hey @travisstaloch , would you accept a PR refactoring `src/codegen.zig`?

## Serious issues
1. `--no-gen-object-api` still imports object API `...T` types and `Unpack` functions
2. Property name collisions with unions can lead to generated code calling non-existent functions. For example:
```fbs
union Type { Null, Int }
table Field { type: Type }
```
generates a non-existent call to `rcv.Type_Type()` instead of the correct `rcv.TypeType()`:
```zig
pub fn UnpackTo(rcv: Field, t: *FieldT, __pack_opts: fb.common.PackOptions) !void {
    if (rcv.Type_()) |_tab| {
        t.type = try TypeT.Unpack(rcv.Type_Type(), _tab, __pack_opts);
    }
}
```
3. Object API optionals should be `optional_field: ?T` instead of `optional_field: ?*T` to prevent unnecessary allocation.
4. Add error printing on invalid codegen (useful for when Zig breaks codegenned syntax and for codegen devs)

## Style issues
1. Remove `_`s from variable names. Zig purposefully disallows private struct members. Also, constants like `__file_indent` are already namespaced to the source file. Parameters like `__builder` can simply be renamed to `builder`.
2. Consistently use `self: Self` instead of inconsitently `rcv: {type}` and `self: {type}`
3. Add option for an index file with all generated types since there's a file generated per table/struct/union which can add up quickly.
4. As for the casing, I think a reason for `Title` over `snake_case` is to prevent parameter name shadowing like:
```zig
pub fn rcv(rcv: Field) bool {
    ...
}
```

This can of course be solved by renaming the parameter to `rcv_` or something similar but adds another layer of complexity.

**Comment by travisstaloch** [comment]
> 3\. Object API optionals should be `optional_field: ?T` instead of `optional_field: ?*T` to prevent unnecessary allocation.

Perhaps this should be the default and the existing behavior put behind a flag for when users need a recursive structure.  I don't want to add too much complexity, but perhaps its needed here?

**Comment by clickingbuttons** [comment]
> Perhaps this should be the default and the existing behavior put behind a flag for when users need a recursive structure.

Ah, I didn't think about recursive structures! Can enums or unions be recursive? If it's only for structs and tables that makes detection simpler.

**Comment by clickingbuttons** [comment]
I've started refactoring and have enum + unions compiling. I was able to eliminate a lot of boilerplate by using `switch (self) { inline else => |field, tag| { ... } }`.

Tomorrow I'll:
- Handle imports + name collision (will favor renaming parameters and modules over renaming functions)
- Implement struct gen
- Test it in https://github.com/clickingbuttons/arrow-zig
- Handle recursion (thanks for mentioning it!) and add a recursive type test (if there isn't already one)
- Make a PR!

**Comment by travisstaloch** [comment]
> > Perhaps this should be the default and the existing behavior put behind a flag for when users need a recursive structure.
> 
> Ah, I didn't think about recursive structures! Can enums or unions be recursive? If it's only for structs and tables that makes detection simpler.

Seems like it would be necessary for unions but not enums.  But if its too much for one PR, we could put this in a follow-up PR.

**Comment by travisstaloch** [comment]
sounds like you've already made some good progress. you might want to run the following to test building all the examples/
```sh
script/test-all.sh
```

**Comment by travisstaloch** [comment]
> * Handle recursion (thanks for mentioning it!) and add a recursive type test (if there isn't already one)

i forget if there anything recursive in examples/.  if not, feel free to add something there.

**Comment by clickingbuttons** [comment]
> But if its too much for one PR, we could put this in a follow-up PR.

That sounds good. The first will probably land around -2000/+1000 which is plenty.

**Comment by travisstaloch** [comment]
> you might want to run the following to test generating and compiling everything in examples/
> 
> ```shell
> script/test-all.sh
> ```

this was wrong. i mixed up projects. but i've just pushed a commit which does this.  

however, this doesn't test much yet (expect for doing a simple ast-check) as there are no dummy tests generated yet.  i'll leave that for later on so as to not conflict with your work.

**Comment by clickingbuttons** [comment]
Today I handled imports by using a index file per `.bfbs` file.

Old:
```zig
const KeyValueT = @import("KeyValue.fb.zig").KeyValueT;

pub const FieldT = struct {
    custom_metadata: std.ArrayListUnmanaged(KeyValueT) = .{},
};
```

New:
```zig
const Schema = @import("Schema_types.zig");

pub const FieldT = struct {
    custom_metadata: std.ArrayListUnmanaged(Schema.KeyValueT) = .{},
};
```

With a nice index file:
```zig
const KeyValue = @import("KeyValue.zig").KeyValue;
const KeyValueT = @import("KeyValue.zig").KeyValueT;
```

I still have to implement struct accessor/mutator functions, but the refactor is shaping up nicely! +525/-2743 so far. Am probably a day or two from a PR.

**Comment by travisstaloch** [comment]
> ```zig
> const Schema = @import("Schema_types.zig");
> ```

I would prefer to keep the ".fb.zig" extension for now.  If you have good reason for removing it, please let me know.  I prefer to keep any changes to a minimum so that other users aren't surprised.

> +525/-2743 so far.

This is exciting but also a little intimidating. I'll be reluctant to accept a PR with this many changes at once and may ask for it to be broken up into smaller pieces.  Just want to be clear so you know what to expect.  I don't want to create any extra work for you.  But I also want to be able to easily digest these changes.

**Comment by clickingbuttons** [comment]
> I would prefer to keep the ".fb.zig" extension for now.
I've just changed it temporarily to make diffing easier.

**Comment by clickingbuttons** [comment]
> I'll be reluctant to accept a PR with this many changes at once and may ask for it to be broken up into smaller pieces.

Hm, I thought about this, but I really am refactoring almost every codegen piece. At this point I'm not even referencing the old implementation. I think it has to be an all-at-once change. For review you can look at the codegen output and check any corner cases you solved in the old implementation. I don't want to make your job hard, either.

I did another +480 / -185 today. The things remaining are the builder methods and namespaced types.

I made a few design choices I'd like your feedback on:
1. Rename `FlatType` to `PackedFlatType`. Rename `FlatTypeT` to `FlatType`. I find the `T` on the end meaningless (it may be an abbreviation of "Type", but both are types), and the `is_object: bool` that floated around to add the `T` is a misnomer. It's more accurate to describe the struct that contains a `fb.Table` as `Packed`. Other possible names are `FlatpackedType` or `FbType`, although `Fb` unfortunately collides with Facebook.
2. Require object API. This allows for `fn PackedType.initFromType(type: Type) -> PackedType` and `fn Type.pack(builder: fb.Builder) -> PackedType`. The old `PackedType.Create(builder: fb.Builder, list, of, every, single, field, as, a, param)` is clunky and not possible to use Zig's comptime reflection on. Comptime reflection reduces boilerplate. It makes the generated code easier to read with fewer, terser lines and the codegen doesn't have to iterate over the fields in `Pack` or `Unpack`.
3. Change `fn VectorFieldLen() -> usize` and `fn VectorFields(i: usize) -> VecFieldType` to `fn Vector() -> []VecFieldType`. I believe this is possible according to the spec since each element is contiguous in memory, but I haven't tested it yet. This would change:
```zig
for (0..packed_struct.VectorFieldLen()) |i| {
  const v = packed_struct.VectorFields(i).?;
}
```
to:
````zig
for (packed_struct.Vector()) |v| {
  _ = v;
}
```

**Comment by travisstaloch** [comment]
These seem like nice changes but I'm hesitant to sign off on them until I can see some full examples of whats generated before and after.  I think you understand that I'd prefer minimize any breaking api changes.  That said, I'm all for cleaning up this project - it definitely needs it.  

Another factor I'm considering is similarity to other popular implementations.  I looked at lots of generated python, cpp and go code while writing this.  I tried to follow them when possible to present a similar api for people who have been using them.  Of course, you can never please everyone and my efforts are not close to perfect.

Excited to see what you're doing.  Maybe push it to a fork and share a link even if its very WIP?

When it comes time to review, my first concern will be differences in generated code.  I'll try to evaluate it first, then look at changes to code in this repo.

**Comment by travisstaloch** [comment]
If you want to see some other generated code: https://github.com/google/flatbuffers/tree/master/python/flatbuffers/reflection

I referenced these while deciding on what the generated api should look like.

**Comment by travisstaloch** [comment]
> 1. Rename `FlatType` to `PackedFlatType`. Rename `FlatTypeT` to `FlatType`.

This seems like a good idea. I think appending the 'T' was just an arbitrary decision on my part and admittedly not very well thought out or descriptive.

**Comment by clickingbuttons** [comment]
> I'd prefer minimize any breaking api changes.

Me too. I think breaking changes are only justified by a better API. Better is subjective but you can measure some things like LOC generated and LOC in example usage. I'm trying to minimize both of those without sacrificing readability.

As for timing, I think the time for breaking API changes is good because Zig the language is still breaking and `flatbufferz` is still young at ~3 mo old.

> Maybe push it to a fork and share a link even if its very WIP?

Sure! I'll push EOD. I expect 1-2 more days before it's ready for a PR.

**Comment by travisstaloch** [comment]
> 2\. Require object API. This allows for ...

I like this a lot. Making Create() accept a single param instead if all of the fields seems like positive change.

> 3\. Change `fn VectorFieldLen() -> usize` and `fn VectorFields(i: usize) -> VecFieldType` to `fn Vector() -> []VecFieldType`

While i personally would prefer this api and agree its more zig friendly, i think this is an unnecessary breaking change.  Its valuable to be able to request `VectorFieldLen()` alone.  

Maybe keep the existing api but add another method `fn Vector()` which returns the slice.  I forget and am assuming its possible to do this without making any allocations.  If not, i think i would reject this change.

**Comment by clickingbuttons** [comment]
> Its valuable to be able to request VectorFieldLen() alone.

How is `VectorFieldLen()` better than `VectorField().len`?

> I forget and am assuming its possible to do this without making any allocations.

I know it is for scalar types. I don't think it will be for non-scalar types.

**Comment by travisstaloch** [comment]
> 2\. The old `PackedType.Create(builder: fb.Builder, list, of, every, single, field, as, a, param)` is clunky and not possible to use Zig's comptime reflection on.

I should say that I'd prefer not to depend on comptime and prefer to default to generating more code.  This results in faster compile times and a cleaner api - one where we don't need a comptime option for increasing @setEvalBranchQuota()

**Comment by travisstaloch** [comment]
> How is `VectorFieldLen()` better than `VectorField().len`?

If you look at the implementation of Table.vectorLen() https://github.com/travisstaloch/flatbufferz/blob/main/src/Table.zig#L65 its very simple and fast.  I don't know what it would require to return the vector as a slice.  If its not just a simple read operation then that would force a slower option and eliminate a fast one.

**Comment by clickingbuttons** [comment]
> This results in faster compile times and a cleaner api

I don't think either of those are true but I'm happy to be proven wrong. Currently you shouldn't have to touch `@setEvalBranchQuota()` since there is no branching. I'm only planning on using comptime in generated code here:
```zig
pub fn init(packed_struct: {0s}) !Self {{
    var res = Self{{}};
    inline for (@typeInfo(Self).Struct.fields) |f| {{
        const getter = @field({0s}, f.name);
        @field(res, f.name) = getter(packed_struct);
    }}
    return res;
}}
```

> If its not just a simple read operation then that would force a slower option and eliminate a fast one.

It's one more read of the vtable to get the pointer to the start of the vector. A slice is just a pointer and a length. I think a `mov` on memory that's already in L1 or L2 will be very fast and not worth the 2 different ways to do the same thing.

Again, I'm happy to be proven wrong and/or validate it with benchmarks. I'm currently more interested in how vectors of structs and vectors of tables are laid out in flatbuffers memory. Do you happen to know?

**Comment by travisstaloch** [comment]
@setEvalBranchQuota() is how you increase the upper limit of comptime instructions. https://ziglang.org/documentation/master/#setEvalBranchQuota

while i understand the appeal of comptime for writing smaller code, its requires more compilation resources and thus doesn't scale as well.  it can also lead to some tricky spots and difficult to understand compilation errors imo.

**Comment by travisstaloch** [comment]
> I'm currently more interested in how vectors of structs and vectors of tables are laid out in flatbuffers memory.

https://flatbuffers.dev/flatbuffers_internals.html search for 'Strings and Vectors'

**Comment by travisstaloch** [comment]
vectors are not contiguous so returning a slice isn't an option without allocating.

**Comment by clickingbuttons** [comment]
This can be closed in favor of smaller issues.

**Comment by travisstaloch** [comment]
Thanks for all of this great feedback and for all of these issues :+1:
