### ISSUE TITLE
Fix --no-gen-object-api

### ISSUE THREAD

**Issue by clickingbuttons** [travisstaloch/flatbufferz#5]
`--no-gen-object-api` still imports object API `...T` types and `Unpack` functions taking a `...T`.

Ideally this flag is just removed and always turned on since it allows for nicer `Unpack` methods.

**Comment by travisstaloch** [comment]
> Ideally this flag is just removed and always turned on since it allows for nicer `Unpack` methods.

Did you mean 'always turned off'?  If so, I agree. Right now, support for this flag is only partially implemented and leads to code that doesn't compile.

I started trying to add more support for it.  But it only leads to more name collisions in generated code.  So I'm going to remove the flag for now.  My apologies to anyone who may have been depending on this, but you will just have to edit the generated source files for now.
